import React, { useState } from 'react';
import { AnalysisResult, Part } from '../types';
import { Cpu, Zap, AlertTriangle, Lightbulb, Box, Check, Printer, ShoppingCart, X, FileDown } from 'lucide-react';

interface AnalysisDisplayProps {
  result: AnalysisResult;
}

const AnalysisDisplay: React.FC<AnalysisDisplayProps> = ({ result }) => {
  const [selectedIndices, setSelectedIndices] = useState<Set<number>>(new Set());
  const [showShoppingList, setShowShoppingList] = useState(false);

  const toggleSelection = (index: number) => {
    const newSelection = new Set(selectedIndices);
    if (newSelection.has(index)) {
      newSelection.delete(index);
    } else {
      newSelection.add(index);
    }
    setSelectedIndices(newSelection);
  };

  const selectedParts = result.parts.filter((_, i) => selectedIndices.has(i));

  const handlePrint = () => {
    const printWindow = window.open('', '_blank', 'height=800,width=800');
    if (!printWindow) return;

    const itemsHtml = selectedParts.map((part, idx) => `
      <tr>
        <td>${idx + 1}</td>
        <td>
          <div class="part-name">${part.name}</div>
          <div class="part-desc">${part.description}</div>
        </td>
        <td><span class="badge">${part.type}</span></td>
        <td style="text-align: center;"><div class="checkbox"></div></td>
      </tr>
    `).join('');

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Shopping List - ${result.deviceName}</title>
          <style>
            @import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap');
            body { 
              font-family: 'Space Grotesk', sans-serif; 
              padding: 40px; 
              color: #1e293b; 
              line-height: 1.5;
            }
            .header {
              border-bottom: 2px solid #e2e8f0;
              padding-bottom: 20px;
              margin-bottom: 30px;
            }
            h1 { 
              color: #0f172a; 
              margin: 0 0 10px 0;
              font-size: 24px;
            }
            .meta { color: #64748b; font-size: 14px; }
            table { width: 100%; border-collapse: collapse; }
            th { 
              text-align: left; 
              padding: 12px 8px; 
              border-bottom: 2px solid #cbd5e1; 
              color: #475569; 
              text-transform: uppercase; 
              font-size: 12px; 
              letter-spacing: 0.05em;
            }
            td { 
              padding: 16px 8px; 
              border-bottom: 1px solid #e2e8f0; 
              vertical-align: top; 
            }
            .part-name { font-weight: 600; color: #0f172a; }
            .part-desc { font-size: 13px; color: #64748b; margin-top: 4px; }
            .badge {
              display: inline-block;
              padding: 4px 8px;
              background: #f1f5f9;
              border: 1px solid #e2e8f0;
              border-radius: 4px;
              font-size: 11px;
              font-weight: 500;
              color: #475569;
            }
            .checkbox { 
              width: 18px; 
              height: 18px; 
              border: 2px solid #cbd5e1; 
              border-radius: 4px; 
              margin: 0 auto; 
            }
            .footer {
              margin-top: 50px;
              padding-top: 20px;
              border-top: 1px solid #e2e8f0;
              text-align: center;
              font-size: 12px;
              color: #94a3b8;
            }
            @media print {
              body { padding: 0; }
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>${result.deviceName}</h1>
            <div class="meta">
              <strong>Function:</strong> ${result.deviceFunction}<br>
              <strong>Generated:</strong> ${new Date().toLocaleDateString()}
            </div>
          </div>
          
          <table>
            <thead>
              <tr>
                <th width="40">#</th>
                <th>Component Details</th>
                <th width="140">Type</th>
                <th width="60" style="text-align: center">Check</th>
              </tr>
            </thead>
            <tbody>
              ${itemsHtml}
            </tbody>
          </table>

          <div class="footer">
            Generated by CircuitHarvester • Build new things with old toys
          </div>
          
          <script>
            // Automatically trigger print when loaded
            window.onload = function() {
              setTimeout(() => {
                window.print();
              }, 500);
            }
          </script>
        </body>
      </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
  };

  const handleExportWord = () => {
    // Generate a simple HTML document compatible with Microsoft Word
    const header = `<html xmlns:o='urn:schemas-microsoft-com:office:office' 
                          xmlns:w='urn:schemas-microsoft-com:office:word' 
                          xmlns='http://www.w3.org/TR/REC-html40'>
      <head><meta charset='utf-8'><title>Shopping List</title></head><body>`;
    
    const footer = "</body></html>";
    
    // We construct the table content manually to ensure it has no React artifacts/classes
    const rows = selectedParts.map((part, i) => `
      <tr>
        <td style="border-bottom:1px solid #ddd; padding:10px;">${i + 1}</td>
        <td style="border-bottom:1px solid #ddd; padding:10px;">
          <b>${part.name}</b><br/>
          <span style="color:#666; font-size:0.9em;">${part.description}</span>
        </td>
        <td style="border-bottom:1px solid #ddd; padding:10px;">${part.type}</td>
        <td style="border-bottom:1px solid #ddd; padding:10px; text-align:center;">[ ]</td>
      </tr>
    `).join('');

    const content = `
      <h1 style="color:#333;">${result.deviceName} - Parts List</h1>
      <p><i>${result.deviceFunction}</i></p>
      <br/>
      <table style="width:100%; border-collapse:collapse; text-align:left;">
        <thead style="background-color:#f5f5f5;">
          <tr>
            <th style="border-bottom:2px solid #999; padding:10px;">#</th>
            <th style="border-bottom:2px solid #999; padding:10px;">Component</th>
            <th style="border-bottom:2px solid #999; padding:10px;">Type</th>
            <th style="border-bottom:2px solid #999; padding:10px;">Check</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>
    `;
    
    const sourceHTML = header + content + footer;
    const source = 'data:application/vnd.ms-word;charset=utf-8,' + encodeURIComponent(sourceHTML);
    const fileDownload = document.createElement("a");
    document.body.appendChild(fileDownload);
    fileDownload.href = source;
    fileDownload.download = `parts-list-${result.deviceName.replace(/\s+/g, '-').toLowerCase()}.doc`;
    fileDownload.click();
    document.body.removeChild(fileDownload);
  };

  return (
    <div className="w-full max-w-4xl mx-auto space-y-8 animate-[fadeIn_0.5s_ease-out] pb-24">
      
      {/* Device Overview Header */}
      <div className="bg-slate-800/80 backdrop-blur-sm border border-slate-700 rounded-2xl p-6 md:p-8 shadow-xl relative overflow-hidden">
        <div className="absolute top-0 right-0 p-4 opacity-10">
          <Cpu size={120} />
        </div>
        <div className="relative z-10">
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-4 mb-4">
            <div>
              <h2 className="text-3xl md:text-4xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-cyan-400">
                {result.deviceName}
              </h2>
              {result.estimatedAge && (
                <span className="inline-block mt-2 px-3 py-1 bg-slate-700 rounded-full text-xs font-medium text-slate-300 uppercase tracking-wider">
                  Era: {result.estimatedAge}
                </span>
              )}
            </div>
          </div>
          <p className="text-slate-300 text-lg leading-relaxed max-w-2xl">
            {result.deviceFunction}
          </p>
        </div>
      </div>

      {/* Safety Warnings */}
      {result.safetyWarnings.length > 0 && (
        <div className="bg-amber-950/40 border border-amber-900/50 rounded-xl p-4 flex gap-4 items-start">
          <AlertTriangle className="text-amber-500 shrink-0 mt-1" />
          <div>
            <h3 className="text-amber-400 font-bold mb-1">Safety First</h3>
            <ul className="list-disc list-inside text-amber-200/80 text-sm space-y-1">
              {result.safetyWarnings.map((warning, idx) => (
                <li key={idx}>{warning}</li>
              ))}
            </ul>
          </div>
        </div>
      )}

      {/* Harvestable Parts Grid */}
      <div className="space-y-4">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-2">
            <Box className="text-emerald-400" />
            <h3 className="text-2xl font-bold text-white">Harvestable Components</h3>
          </div>
          <p className="text-sm text-slate-400 hidden md:block">
            Select items to build a shopping list
          </p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {result.parts.map((part, index) => {
            const isSelected = selectedIndices.has(index);
            return (
              <div 
                key={index} 
                id={`part-${index}`}
                onClick={() => toggleSelection(index)}
                className={`group cursor-pointer relative overflow-hidden rounded-xl p-5 transition-all duration-300 flex flex-col h-full border 
                  ${isSelected 
                    ? 'bg-slate-800 border-emerald-500 shadow-[0_0_20px_rgba(16,185,129,0.2)]' 
                    : 'bg-slate-800 border-slate-700 hover:border-slate-500'}`}
              >
                {/* Selection Checkbox */}
                <div className={`absolute top-4 right-4 w-6 h-6 rounded-md border-2 flex items-center justify-center transition-colors z-20
                  ${isSelected ? 'bg-emerald-500 border-emerald-500' : 'border-slate-600 group-hover:border-slate-400'}`}>
                  {isSelected && <Check className="w-4 h-4 text-white" />}
                </div>

                {/* Index Number Watermark */}
                <div className="absolute top-2 right-12 text-6xl font-bold text-slate-700/20 pointer-events-none select-none">
                  {index + 1}
                </div>

                <div className="flex justify-between items-start mb-3 relative z-10">
                  <div className="flex items-center gap-3">
                    <div className={`w-8 h-8 rounded-full border flex items-center justify-center font-bold text-sm transition-colors
                      ${isSelected ? 'bg-emerald-500 text-white border-emerald-500' : 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30'}`}>
                      {index + 1}
                    </div>
                    <div className="bg-slate-900 rounded-lg p-2 border border-slate-700">
                       <Zap className="w-4 h-4 text-cyan-400" />
                    </div>
                  </div>
                </div>
                
                <div className="pr-8">
                  <h4 className={`text-xl font-bold mb-1 transition-colors relative z-10 ${isSelected ? 'text-emerald-400' : 'text-white'}`}>
                    {part.name}
                  </h4>
                  <p className="text-slate-400 text-xs font-mono mb-3 relative z-10">{part.type}</p>
                </div>
                
                <p className="text-slate-300 text-sm mb-4 flex-grow relative z-10">
                  {part.description}
                </p>

                <div className="mt-auto pt-4 border-t border-slate-700/50 relative z-10">
                  <div className="flex items-center gap-2 mb-2">
                    <Lightbulb className="w-4 h-4 text-amber-400" />
                    <span className="text-xs font-bold text-amber-400 uppercase">Project Ideas</span>
                  </div>
                  <ul className="space-y-1">
                    {part.projectIdeas.map((idea, i) => (
                      <li key={i} className="text-sm text-slate-400 pl-2 border-l-2 border-slate-700">
                        {idea}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Floating Action Bar for Selection */}
      <div className={`fixed bottom-6 left-1/2 -translate-x-1/2 bg-slate-800 border border-slate-700 text-white px-6 py-3 rounded-full shadow-2xl transition-all duration-300 z-40 flex items-center gap-4
        ${selectedIndices.size > 0 ? 'translate-y-0 opacity-100' : 'translate-y-24 opacity-0 pointer-events-none'}`}>
        <span className="font-bold text-emerald-400">{selectedIndices.size} selected</span>
        <div className="h-4 w-px bg-slate-600" />
        <button 
          onClick={() => setShowShoppingList(true)}
          className="flex items-center gap-2 hover:text-emerald-400 transition-colors"
        >
          <ShoppingCart className="w-5 h-5" />
          <span className="font-medium">View List</span>
        </button>
      </div>

      {/* Shopping List Modal */}
      {showShoppingList && (
        <div className="fixed inset-0 z-50 bg-black/90 flex items-center justify-center p-4 backdrop-blur-sm">
          <div className="bg-white text-slate-900 w-full max-w-2xl max-h-[90vh] rounded-2xl flex flex-col shadow-2xl">
            
            {/* Modal Header */}
            <div className="p-6 border-b border-slate-200 flex justify-between items-center bg-slate-50 rounded-t-2xl">
              <div>
                <h3 className="text-2xl font-bold flex items-center gap-2">
                  <ShoppingCart className="text-emerald-600" />
                  Project Shopping List
                </h3>
                <p className="text-slate-500 text-sm mt-1">
                  Parts harvested from {result.deviceName}
                </p>
              </div>
              <button 
                onClick={() => setShowShoppingList(false)}
                className="text-slate-400 hover:text-slate-600 transition-colors p-2 hover:bg-slate-100 rounded-full"
              >
                <X className="w-6 h-6" />
              </button>
            </div>

            {/* Content Preview */}
            <div className="flex-1 overflow-y-auto p-6">
              <div className="space-y-6">
                <div className="bg-blue-50 border border-blue-100 rounded-lg p-4 text-sm text-blue-800 flex gap-3">
                  <Lightbulb className="w-5 h-5 text-blue-600 shrink-0" />
                  <p>
                    Use this list to verify specs for connectors (like pin pitch, voltage) or to find compatible add-ons for your projects.
                  </p>
                </div>

                <table className="w-full text-left border-collapse">
                  <thead>
                    <tr className="border-b-2 border-slate-200">
                      <th className="py-3 px-2 text-sm font-bold text-slate-500 uppercase">#</th>
                      <th className="py-3 px-2 text-sm font-bold text-slate-500 uppercase">Component</th>
                      <th className="py-3 px-2 text-sm font-bold text-slate-500 uppercase">Type / Specs</th>
                      <th className="py-3 px-2 text-sm font-bold text-slate-500 uppercase w-12 text-center">Chk</th>
                    </tr>
                  </thead>
                  <tbody>
                    {selectedParts.map((part, idx) => (
                      <tr key={idx} className="border-b border-slate-100 last:border-0 hover:bg-slate-50">
                        <td className="py-4 px-2 font-mono text-slate-400 text-sm align-top">
                          {idx + 1}
                        </td>
                        <td className="py-4 px-2 align-top">
                          <div className="font-bold text-slate-900">{part.name}</div>
                          <div className="text-sm text-slate-500 mt-1">{part.description}</div>
                        </td>
                        <td className="py-4 px-2 align-top">
                          <span className="inline-block px-2 py-1 bg-slate-100 rounded text-xs font-medium text-slate-600 border border-slate-200">
                            {part.type}
                          </span>
                        </td>
                        <td className="py-4 px-2 text-center align-top">
                          <div className="w-5 h-5 border-2 border-slate-300 rounded mx-auto" />
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Modal Footer */}
            <div className="p-6 border-t border-slate-200 bg-slate-50 rounded-b-2xl flex flex-col sm:flex-row justify-between items-center gap-4">
              <span className="text-sm text-slate-500 hidden sm:inline">
                {selectedParts.length} items ready for export
              </span>
              <div className="flex flex-wrap gap-3 w-full sm:w-auto justify-end">
                <button
                  onClick={() => setShowShoppingList(false)}
                  className="px-4 py-3 rounded-xl border border-slate-300 text-slate-700 font-bold hover:bg-white hover:border-slate-400 transition-all text-sm"
                >
                  Close
                </button>
                <button
                  onClick={handleExportWord}
                  className="px-4 py-3 rounded-xl bg-blue-600 text-white font-bold hover:bg-blue-500 shadow-lg shadow-blue-200 transition-all flex items-center justify-center gap-2 text-sm"
                >
                  <FileDown className="w-4 h-4" />
                  Export .docx
                </button>
                <button
                  onClick={handlePrint}
                  className="px-4 py-3 rounded-xl bg-emerald-600 text-white font-bold hover:bg-emerald-500 shadow-lg shadow-emerald-200 transition-all flex items-center justify-center gap-2 text-sm"
                >
                  <Printer className="w-4 h-4" />
                  Print / PDF
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AnalysisDisplay;